### ISSUE TITLE
Clarification Needed: Specific Errors Managed by TwitterTokenUnlocker

### ISSUE THREAD

**Issue by ahmetbbt** [Twitter-Tools/TwitterTokensUnlocker#1]
I have noticed that tokens can become invalid for several reasons. I have identified at least two specific error messages that could potentially indicate a token issue:
- AuthorizationError
- Could not authenticate you

Could you clarify which specific error(s) the TwitterTokenUnlocker project is designed to address? More specifically, which response from Twitter should indicate that the token needs to be unlocked by this project?

Thank you for your assistance!

**Comment by Twitter-Tools** [comment]
Token gets deleted = cannot be unlocked using this tool.
Tokens gets locked = token can be unlocked using this tool. this happens when Twitter asks you to solve a captcha because of suspicious actions

**Comment by ahmetbbt** [comment]
If you use Twitter via the UI, you can of course understand when a captcha will appear and when you will be logged out. But that's not my question. I don't use Twitter via the UI, so I'm not a regular user. I am an API user.

In other words, whatever is in the response returned from the API is token deleted, whatever is token is locked?

**Comment by ahmetbbt** [comment]
In the response returned, if there is an `AuthorizationError` in `/errors/0/name`, I understand that the token is locked.
Here is an example AuthorizationError response:
```
{
  "errors": [
    {
      "message": "Authorization: Denied by access control: To protect our users from spam and other malicious activity, this account is temporarily locked. Please log in to https://twitter.com to unlock your account.; Missing LdapGroup(weaverbird-admins)",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "user",
        "result"
      ],
      "extensions": {
        "name": "AuthorizationError",
        "source": "Client",
        "bounce": {
          "bounce_location": "https://twitter.com/account/access",
          "sub_error_code": 0
        },
        "code": 326,
        "kind": "Permissions",
        "tracing": {
          "trace_id": "xvrptkd3kssow2"
        }
      },
      "bounce": {
        "bounce_location": "https://twitter.com/account/access",
        "sub_error_code": 0
      },
      "code": 326,
      "kind": "Permissions",
      "name": "AuthorizationError",
      "source": "Client",
      "tracing": {
        "trace_id": "xvrptkd3kssow2"
      }
    }
  ],
  "data": {
    "user": {}
  },
  "remains": 49,
  "remainReset": 1712593654
}
```
However, I noticed that even though AuthorizationError returned a few times, I could continue using it. So, I sent the request in the following order:

- usertweets request -> success
- usertweets request -> AuthorizationError
- usertweets request -> success
- usertweets request -> success

But it usually goes like this:
- usertweets request -> success
- usertweets request -> AuthorizationError
- usertweets request -> AuthorizationError
- usertweets request -> AuthorizationError
...

**Comment by Twitter-Tools** [comment]
It's really not that hard to figure it out. If you still cannot figure it out just look at any twitter token checker on github and you'll see exactly how to determine if its locked/unlocked/deleted
